### ISSUE TITLE
Light list: missing lists?

### ISSUE THREAD

**Issue by rd-su** [Zelo72/adguard#2]
Hi,

I'm new to your lists, and you are doing a great job!

If I'm not mistaken, it seems that Light version lists doesn't have all the Personal lists, at least in the lists description:

https://raw.githubusercontent.com/infinitytec/blocklists/master/ads-and-trackers.txt
https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_ABP
https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US%2Bmost_used_ad_and_tracking_networks

Thanks!

**Comment by Zelo72** [comment]
Hello, thanks for the hint, have included the personal list in the light list.
