### ISSUE TITLE
sportsbet.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [Zelo72/adguard#7]
Can you please check if ```sportsbet.com.au``` should be removed from multi list? It's an Australian online gambling website, would like to know why it's blocked.

**Comment by Zelo72** [comment]
Hi @gyCfjSnO,

thans for the report. Blocked by [AntiPopAds-Re](https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/domains.txt). `sportsbet.com.au` has been removed from my lists.

Greets,
Gerd
